import fs from "fs/promises";
import path from "path";
import { logger } from "./logger";

// Marker written into auto-generated Dockerfiles so we know to regenerate them
// on the next deploy. User-provided Dockerfiles won't have this line.
const AUTO_GENERATED_MARKER = "# VersionGate:auto-generated";

/** True if this file was produced by ensureDockerfile (including legacy without BuildKit # syntax line). */
function isOurAutoGeneratedDockerfile(content: string): boolean {
  const lines = content.split("\n");
  if (lines[0] === AUTO_GENERATED_MARKER) return true;
  if (lines[0]?.startsWith("# syntax=") && lines[1] === AUTO_GENERATED_MARKER) return true;
  return false;
}

export interface ProjectBuildOptions {
  packageManager?: string | null;
  installCommand?: string | null;
  buildCommand?: string | null;
  startCommand?: string | null;
}

/**
 * Ensures a Dockerfile exists in the given build context directory.
 *
 * - If a Dockerfile exists WITHOUT the auto-generated marker → user's own file, leave it.
 * - If a Dockerfile exists WITH the marker → stale auto-generated, regenerate it.
 * - If no Dockerfile → generate one.
 *
 * Detection order: buildContextDir first, then repoRootDir, then immediate subdirs.
 * Returns the directory where the Dockerfile was written.
 */
export async function ensureDockerfile(
  buildContextDir: string,
  appPort: number,
  repoRootDir?: string,
  options?: ProjectBuildOptions
): Promise<string> {
  const dockerfilePath = path.join(buildContextDir, "Dockerfile");

  try {
    const existing = await fs.readFile(dockerfilePath, "utf-8");
    if (!isOurAutoGeneratedDockerfile(existing)) {
      // User's own Dockerfile — respect it
      logger.debug({ buildContextDir }, "Dockerfile found — skipping generation");
      return buildContextDir;
    }
    // Auto-generated from a previous deploy — fall through to regenerate
    logger.debug({ buildContextDir }, "Stale auto-generated Dockerfile detected — regenerating");
  } catch {
    // No Dockerfile — generate one
  }

  // Build candidate list: specified buildContext → repo root → immediate subdirs.
  const root = repoRootDir ?? buildContextDir;
  const dirsToTry: string[] = [buildContextDir];
  if (root !== buildContextDir) dirsToTry.push(root);

  try {
    const entries = await fs.readdir(root, { withFileTypes: true });
    const subdirs = entries
      .filter((e) => e.isDirectory() && !e.name.startsWith(".") && e.name !== "node_modules")
      .map((e) => path.join(root, e.name));
    logger.debug({ root, subdirs }, "Scanning repo for project files");
    for (const sub of subdirs) {
      if (!dirsToTry.includes(sub)) dirsToTry.push(sub);
    }
  } catch {
    // readdir failed — skip subdir scan
  }

  for (const dir of dirsToTry) {
    const content = await tryGenerateDockerfile(dir, appPort, options);
    if (content !== null) {
      const targetDockerfile = path.join(dir, "Dockerfile");
      await fs.writeFile(targetDockerfile, content, "utf-8");
      logger.info({ dir, appPort }, "Dockerfile auto-generated");
      return dir;
    }
  }

  throw new Error(
    "Could not detect project type. Add a Dockerfile to your repository and redeploy."
  );
}

// ── Detector ─────────────────────────────────────────────────────────────────

/** Returns generated Dockerfile content, or null if the project type is undetectable. */
export async function tryGenerateDockerfile(
  repoDir: string,
  appPort: number,
  options?: ProjectBuildOptions
): Promise<string | null> {
  // 0. Explicit Custom Command Override
  if (options?.installCommand || options?.buildCommand || options?.startCommand) {
    return buildCustomDockerfile(appPort, options);
  }

  const explicitPm = (options?.packageManager || "auto").toLowerCase();

  // 1. Node.js (package.json or explicit Node PM)
  const pkgJsonPath = path.join(repoDir, "package.json");
  try {
    const raw = await fs.readFile(pkgJsonPath, "utf-8");
    const pkg = JSON.parse(raw) as Record<string, unknown>;
    return await buildNodeDockerfile(repoDir, pkg, appPort, options);
  } catch {
    if (["bun", "pnpm", "yarn", "npm"].includes(explicitPm)) {
      return buildNodeDockerfile(repoDir, {}, appPort, options);
    }
  }

  // 2. Python (uv, poetry, pipenv, requirements.txt, pyproject.toml)
  const hasUvLock = await fileExists(repoDir, "uv.lock");
  const hasPoetryLock = await fileExists(repoDir, "poetry.lock");
  const hasPipfile = (await fileExists(repoDir, "Pipfile")) || (await fileExists(repoDir, "Pipfile.lock"));
  const hasPyproject = await fileExists(repoDir, "pyproject.toml");
  const hasReqs = await fileExists(repoDir, "requirements.txt");

  let pyprojectContent = "";
  if (hasPyproject) {
    try {
      pyprojectContent = await fs.readFile(path.join(repoDir, "pyproject.toml"), "utf-8");
    } catch {
      // ignore
    }
  }

  if (explicitPm === "uv" || hasUvLock || pyprojectContent.includes("[tool.uv]")) {
    return buildPythonUvDockerfile(appPort);
  }
  if (explicitPm === "poetry" || hasPoetryLock || pyprojectContent.includes("[tool.poetry]")) {
    return buildPythonPoetryDockerfile(appPort);
  }
  if (explicitPm === "pipenv" || hasPipfile) {
    return buildPythonPipenvDockerfile(appPort);
  }
  if (explicitPm === "pip" || hasReqs || hasPyproject) {
    return buildPythonDockerfile(appPort);
  }

  // 3. Rust (Cargo.toml or explicit cargo PM)
  if (explicitPm === "cargo" || (await fileExists(repoDir, "Cargo.toml"))) {
    return buildRustDockerfile(appPort);
  }

  // 4. Go (go.mod)
  try {
    await fs.access(path.join(repoDir, "go.mod"));
    return buildGoDockerfile(appPort);
  } catch {
    // not Go
  }

  // 5. PHP (composer.json, index.php, or explicit composer PM)
  if (
    explicitPm === "composer" ||
    (await fileExists(repoDir, "composer.json")) ||
    (await fileExists(repoDir, "index.php"))
  ) {
    return buildPhpDockerfile(appPort);
  }

  // 6. Static HTML / no build step (index.html or index.htm at root of this directory)
  if ((await fileExists(repoDir, "index.html")) || (await fileExists(repoDir, "index.htm"))) {
    return buildStaticHtmlDockerfile(appPort);
  }

  return null;
}

// ── Node.js ───────────────────────────────────────────────────────────────────

async function buildNodeDockerfile(
  repoDir: string,
  pkg: Record<string, unknown>,
  appPort: number,
  options?: ProjectBuildOptions
): Promise<string> {
  const scripts = (pkg.scripts ?? {}) as Record<string, string>;
  const hasBuild = Boolean(scripts.build);
  const startScript = scripts.start ?? "";
  const buildScript = scripts.build ?? "";

  const explicitPm = (options?.packageManager || "auto").toLowerCase();
  if (explicitPm === "bun") return buildBunDockerfile(appPort, hasBuild);
  if (explicitPm === "pnpm") return buildPnpmDockerfile(appPort, hasBuild);
  if (explicitPm === "yarn") return buildYarnDockerfile(appPort, hasBuild);
  if (explicitPm === "npm") return buildNpmDockerfile(appPort, hasBuild, false);

  // Check if start/build scripts explicitly call bun — strongest signal
  const scriptUsesBun = /\bbun\b/.test(startScript) || /\bbun\b/.test(buildScript);
  if (scriptUsesBun) {
    return buildBunDockerfile(appPort, hasBuild);
  }

  // Fall back to lock file detection
  const hasBunLock  = (await fileExists(repoDir, "bun.lockb")) || (await fileExists(repoDir, "bun.lock"));
  const hasYarnLock = await fileExists(repoDir, "yarn.lock");
  const hasPnpmLock = await fileExists(repoDir, "pnpm-lock.yaml");

  if (hasBunLock)  return buildBunDockerfile(appPort, hasBuild);
  if (hasYarnLock) return buildYarnDockerfile(appPort, hasBuild);
  if (hasPnpmLock) return buildPnpmDockerfile(appPort, hasBuild);
  const hasNpmLock = await fileExists(repoDir, "package-lock.json");
  return buildNpmDockerfile(appPort, hasBuild, hasNpmLock);
}

function buildNpmDockerfile(
  appPort: number,
  hasBuild: boolean,
  useCi: boolean
): string {
  // npm ci needs package-lock.json in context (COPY package*.json).
  const installCmd = useCi
    ? "npm ci --legacy-peer-deps --no-audit --no-fund"
    : "npm install --legacy-peer-deps --no-audit --no-fund";

  return lines([
    "# syntax=docker/dockerfile:1",
    AUTO_GENERATED_MARKER,
    "FROM node:20-alpine",
    "",
    "WORKDIR /app",
    "",
    "COPY package*.json ./",
    "RUN --mount=type=cache,target=/root/.npm \\",
    `    ${installCmd} && npm cache clean --force`,
    "",
    "COPY . .",
    "",
    ...(hasBuild ? ["RUN npm run build", ""] : []),
    `EXPOSE ${appPort}`,
    "",
    'CMD ["npm", "start"]',
  ]);
}

function buildYarnDockerfile(appPort: number, hasBuild: boolean): string {
  return lines([
    AUTO_GENERATED_MARKER,
    "FROM node:20-alpine",
    "",
    "WORKDIR /app",
    "",
    "COPY package.json yarn.lock ./",
    "RUN yarn install --frozen-lockfile",
    "",
    "COPY . .",
    "",
    ...(hasBuild ? ["RUN yarn build", ""] : []),
    `EXPOSE ${appPort}`,
    "",
    'CMD ["yarn", "start"]',
  ]);
}

function buildPnpmDockerfile(appPort: number, hasBuild: boolean): string {
  return lines([
    AUTO_GENERATED_MARKER,
    "FROM node:20-alpine",
    "",
    "RUN npm install -g pnpm",
    "",
    "WORKDIR /app",
    "",
    "COPY package.json pnpm-lock.yaml ./",
    "RUN pnpm install --frozen-lockfile",
    "",
    "COPY . .",
    "",
    ...(hasBuild ? ["RUN pnpm run build", ""] : []),
    `EXPOSE ${appPort}`,
    "",
    'CMD ["pnpm", "start"]',
  ]);
}

function buildBunDockerfile(appPort: number, hasBuild: boolean): string {
  return lines([
    AUTO_GENERATED_MARKER,
    "FROM oven/bun:alpine",
    "",
    "WORKDIR /app",
    "",
    "COPY package.json bun.lock* bun.lockb* ./",
    "RUN bun install",
    "",
    "COPY . .",
    "",
    ...(hasBuild ? ["RUN bun run build", ""] : []),
    `EXPOSE ${appPort}`,
    "",
    'CMD ["bun", "run", "start"]',
  ]);
}

// ── Python ────────────────────────────────────────────────────────────────────

function buildPythonDockerfile(appPort: number): string {
  return lines([
    AUTO_GENERATED_MARKER,
    "FROM python:3.11-slim",
    "",
    "WORKDIR /app",
    "",
    "COPY requirements.txt .",
    "RUN pip install --no-cache-dir -r requirements.txt",
    "",
    "COPY . .",
    "",
    `EXPOSE ${appPort}`,
    "",
    'CMD ["python", "app.py"]',
  ]);
}

function buildPythonUvDockerfile(appPort: number): string {
  return lines([
    "# syntax=docker/dockerfile:1",
    AUTO_GENERATED_MARKER,
    "FROM python:3.11-slim",
    "COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv",
    "WORKDIR /app",
    "COPY pyproject.toml uv.lock* ./",
    "RUN uv sync --frozen --no-cache || uv pip install --system -r requirements.txt || true",
    "COPY . .",
    "",
    `EXPOSE ${appPort}`,
    "",
    'CMD ["uv", "run", "python", "app.py"]',
  ]);
}

function buildPythonPoetryDockerfile(appPort: number): string {
  return lines([
    "# syntax=docker/dockerfile:1",
    AUTO_GENERATED_MARKER,
    "FROM python:3.11-slim",
    "WORKDIR /app",
    "RUN pip install --no-cache-dir poetry",
    "COPY pyproject.toml poetry.lock* ./",
    "RUN poetry config virtualenvs.create false && (poetry install --no-root --no-interaction --no-ansi || true)",
    "COPY . .",
    "",
    `EXPOSE ${appPort}`,
    "",
    'CMD ["poetry", "run", "python", "app.py"]',
  ]);
}

function buildPythonPipenvDockerfile(appPort: number): string {
  return lines([
    "# syntax=docker/dockerfile:1",
    AUTO_GENERATED_MARKER,
    "FROM python:3.11-slim",
    "WORKDIR /app",
    "RUN pip install --no-cache-dir pipenv",
    "COPY Pipfile Pipfile.lock* ./",
    "RUN pipenv install --system --deploy || pipenv install --system",
    "COPY . .",
    "",
    `EXPOSE ${appPort}`,
    "",
    'CMD ["python", "app.py"]',
  ]);
}

// ── Custom Dockerfile Override ───────────────────────────────────────────────

function buildCustomDockerfile(appPort: number, options: ProjectBuildOptions): string {
  const pm = (options.packageManager || "auto").toLowerCase();
  let baseImage = "node:20-alpine";
  let preInstall = "";

  if (pm === "bun") {
    baseImage = "oven/bun:alpine";
  } else if (pm === "pnpm") {
    baseImage = "node:20-alpine";
    preInstall = "RUN npm install -g pnpm";
  } else if (pm === "yarn") {
    baseImage = "node:20-alpine";
  } else if (pm === "pip" || pm === "uv" || pm === "poetry" || pm === "pipenv") {
    baseImage = "python:3.11-slim";
    if (pm === "uv") {
      preInstall = "COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv";
    } else if (pm === "poetry") {
      preInstall = "RUN pip install --no-cache-dir poetry";
    } else if (pm === "pipenv") {
      preInstall = "RUN pip install --no-cache-dir pipenv";
    }
  } else if (pm === "cargo") {
    baseImage = "rust:1-alpine";
  } else if (pm === "composer") {
    baseImage = "php:8.3-cli-alpine";
    preInstall = "COPY --from=composer:latest /usr/bin/composer /usr/bin/composer";
  }

  const installCmd = options.installCommand?.trim();
  const buildCmd = options.buildCommand?.trim();
  const startCmd = options.startCommand?.trim() || "npm start";

  return lines([
    "# syntax=docker/dockerfile:1",
    AUTO_GENERATED_MARKER,
    `FROM ${baseImage}`,
    "",
    "WORKDIR /app",
    "",
    ...(preInstall ? [preInstall, ""] : []),
    "COPY . .",
    "",
    ...(installCmd ? [`RUN ${installCmd}`, ""] : []),
    ...(buildCmd ? [`RUN ${buildCmd}`, ""] : []),
    `EXPOSE ${appPort}`,
    "",
    `CMD ["sh", "-c", ${JSON.stringify(startCmd)}]`,
  ]);
}

// ── Static HTML (nginx) ─────────────────────────────────────────────────────────

/** Serves files from the image root with nginx. Requires `index.html` or `index.htm` in the build context. */
function buildStaticHtmlDockerfile(appPort: number): string {
  const p = String(appPort);
  return lines([
    AUTO_GENERATED_MARKER,
    "FROM nginx:1.25-alpine",
    "",
    "COPY . /usr/share/nginx/html",
    "RUN rm -f /etc/nginx/conf.d/default.conf && \\",
    "    printf '%s\\n' \\",
    "    'server {' \\",
    `    '    listen ${p};' \\`,
    "    '    server_name localhost;' \\",
    "    '    root /usr/share/nginx/html;' \\",
    "    '    index index.html index.htm;' \\",
    "    '    location = /health {' \\",
    "    '        access_log off;' \\",
    "    '        add_header Content-Type text/plain;' \\",
    "    '        return 200 \"healthy\";' \\",
    "    '    }' \\",
    "    '    location / {' \\",
    "    '        try_files $uri $uri/ $uri.html /index.html =404;' \\",
    "    '    }' \\",
    "    '}' > /etc/nginx/conf.d/default.conf",
    "",
    `EXPOSE ${p}`,
    "",
    'CMD ["nginx", "-g", "daemon off;"]',
  ]);
}

// ── Go ────────────────────────────────────────────────────────────────────────

function buildGoDockerfile(appPort: number): string {
  return lines([
    AUTO_GENERATED_MARKER,
    "FROM golang:1.22-alpine AS builder",
    "WORKDIR /app",
    "COPY go.mod go.sum* ./",
    "RUN go mod download",
    "COPY . .",
    "RUN go build -o server .",
    "",
    "FROM alpine:latest",
    "WORKDIR /app",
    "COPY --from=builder /app/server .",
    `EXPOSE ${appPort}`,
    'CMD ["./server"]',
  ]);
}

// ── Rust ──────────────────────────────────────────────────────────────────────

function buildRustDockerfile(appPort: number): string {
  return lines([
    "# syntax=docker/dockerfile:1",
    AUTO_GENERATED_MARKER,
    "FROM rust:1-alpine AS builder",
    "RUN apk add --no-cache musl-dev",
    "WORKDIR /app",
    "COPY Cargo.toml Cargo.lock* ./",
    "COPY . .",
    "RUN cargo build --release",
    "",
    "FROM alpine:latest",
    "RUN apk add --no-cache ca-certificates",
    "WORKDIR /app",
    "COPY --from=builder /app /app",
    `EXPOSE ${appPort}`,
    "",
    'CMD ["sh", "-c", "exec $(find /app/target/release -maxdepth 1 -type f -executable | head -n 1)"]',
  ]);
}

// ── PHP ───────────────────────────────────────────────────────────────────────

function buildPhpDockerfile(appPort: number): string {
  const p = String(appPort);
  return lines([
    "# syntax=docker/dockerfile:1",
    AUTO_GENERATED_MARKER,
    "FROM php:8.3-cli-alpine",
    "WORKDIR /app",
    "COPY --from=composer:latest /usr/bin/composer /usr/bin/composer",
    "COPY composer.json* composer.lock* ./",
    "RUN if [ -f composer.json ]; then composer install --no-dev --prefer-dist --no-interaction || true; fi",
    "COPY . .",
    "",
    `EXPOSE ${p}`,
    "",
    `CMD ["php", "-S", "0.0.0.0:${p}", "-t", "."]`,
  ]);
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function lines(arr: string[]): string {
  return arr.join("\n") + "\n";
}

async function fileExists(dir: string, filename: string): Promise<boolean> {
  try {
    await fs.access(path.join(dir, filename));
    return true;
  } catch {
    return false;
  }
}
